name: koishi
description: A mobile frontend for Koishi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  get: ^4.6.1
  get_storage: ^2.0.3
  connectivity: ^3.0.6
  jwt_decode: ^0.3.1
  intl: ^0.17.0
  date_time_picker: ^2.1.0
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/